name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t app_demo:latest
          docker run --name container_demo -p 8080:8080 -h 0.0.0.0 app_demo:latest
          docker push app_demo:latest
